/* Shared hero render data — NO side effects (safe to import). Consumed by
 * render-one.ts (renders a single id) and render-driver.ts (spawns one process
 * per image with a hard kill-timeout). Style matches docs/KINDLE_HERO_PROMPTS.md. */
import type { ImageSize } from '../src/services/openai/openai.js';

export const PREAMBLE =
  'A 19th-century naturalist field-guide illustration in the tradition of hand-colored ' +
  'botanical and zoological plates — confident, expressive pen-and-ink linework in warm ' +
  'sepia ink finished with rich, saturated watercolor and gouache, like a freshly ' +
  'hand-colored vintage chromolithograph plate. Reference: Audubon, Ernest Thompson Seton, ' +
  'Redoute. Color is bold, luminous and vivid — never faded, muted, pale, neon, or digital. ' +
  'Anatomically and botanically accurate to field-guide standard. Light is warm, soft and ' +
  'directional, as if from a high window in an autumn study. Painted on aged fibrous ' +
  'parchment with subtle patina; whites are the parchment itself, never bright paper-white; ' +
  'soft feathered wash edges. Mood: contemplative, reverent, expedition-journal. Full-bleed ' +
  'single hero subject. Museum-grade — a print someone would frame.';
export const NEGATIVES =
  'ABSOLUTELY NO text, letters, words, numbers, labels, captions, titles, signatures, ' +
  'watermarks, or borders of any kind. No photography or photorealism; no 3D render, flat ' +
  'vector, isometric, low-poly, anime, manga, cartoon, or comic linework; no anthropomorphized ' +
  'animals or cartoon expressions; no modern or man-made objects unless explicitly named.';
export const MODIFIER: Record<string, string> = {
  region: 'A wide, high-vantage establishing scene with big transitional skies.',
  animals: 'Dynamic and alive — captured mid-behavior, with golden-hour or dawn/dusk drama.',
  plants: 'Intimate botanical framing with dewy backlight.',
  trees: 'Look upward — grandeur, age, and atmosphere (mist, light shafts, dramatic sky).',
  fungi: 'Low, ground-level, shallow focus, emerging from forest-floor shadow.',
  terrain: 'A grand vista with the weather as a character; sense of exploration.',
  survival: 'Practical and human — hands and action in working light.',
  bushcraft: 'Warm, handcrafted, inviting — firelit and amber.',
  section: 'An atmospheric, evocative still scene — warm, inviting, quietly cinematic.',
};
export const SIZE: Record<string, ImageSize> = { P: '1024x1536', L: '1536x1024', S: '1024x1024' };

export interface Hero { id: string; slug: string; chapter: keyof typeof MODIFIER; o: 'P' | 'L' | 'S'; body: string; }

export const HEROES: Hero[] = [
  { id: 'I', slug: 'introduction', chapter: 'section', o: 'L', body: 'A single narrow trail dissolving into misty old-growth forest at first light, soft god-rays through the trunks, the wild opening up ahead.' },
  { id: 'G', slug: 'glossary', chapter: 'section', o: 'L', body: "A naturalist's field desk at dusk in lamplight: a pinned feather, a pressed maple leaf, a brass hand lens, and an open leather journal on aged wood." },
  { id: 'A', slug: 'about-series', chapter: 'section', o: 'L', body: 'A weathered leather journal and a glowing oil lantern beside a dying campfire under a vast field of stars, boreal silhouettes around.' },
  { id: '01', slug: 'bones-of-the-land', chapter: 'region', o: 'L', body: 'A glacier-carved U-shaped valley with a single perched erratic boulder on the ridge, a river threading the valley floor, low golden side-light, deep autumn.' },
  { id: '02', slug: 'three-zones', chapter: 'region', o: 'L', body: 'A sweeping morning vista where salt marsh rises through northern hardwood and dark spruce-fir to bare alpine tundra in stacked bands.' },
  { id: '03', slug: 'climate-seasons', chapter: 'region', o: 'L', body: "One mountainside caught at the turn of the year: half ablaze in autumn fire, half dusted with the season's first snow, midday clarity." },
  { id: '04', slug: 'first-peoples', chapter: 'region', o: 'L', body: 'A quiet river bend in dawn mist with a worn portage footpath through ancient forest, no people, ancestral stillness.' },
  { id: '05', slug: 'key-hazards', chapter: 'region', o: 'L', body: 'A lone hiker dwarfed at a fog-swallowed trail junction as weather closes in, the indifferent scale of the wilderness, overcast.' },
  { id: '06', slug: 'weather-above-treeline', chapter: 'region', o: 'P', body: 'A rime-ice-encrusted summit cairn in screaming wind with a sudden knife of clear sky tearing through racing storm cloud, winter.' },
  { id: '07', slug: 'ticks-lyme', chapter: 'animals', o: 'S', body: 'Extreme macro of a single deer tick questing on the tip of a grass blade at a sunlit trail edge, sun flaring behind, ominous tiny menace.' },
  { id: '08', slug: 'moose-hazard', chapter: 'animals', o: 'L', body: 'A massive bull moose feeding chest-deep in a mist-covered beaver pond at sunrise, head streaming water, pond weed trailing, boreal forest, autumn.' },
  { id: '09', slug: 'spring-river-crossings', chapter: 'terrain', o: 'P', body: 'Snowmelt water churning white over dark boulders, spray catching cold light, a single trekking pole probing the powerful current.' },
  { id: '10', slug: 'hypothermia', chapter: 'region', o: 'L', body: 'A hunched lone figure silhouetted against driving cold rain on a bare exposed ridge, daylight failing to blue dusk, the creeping cold.' },
  { id: '11', slug: 'spruce-traps', chapter: 'region', o: 'P', body: 'A claustrophobic tight boreal spruce thicket in deep soft snow with a hidden dark hollow at a tree well, cold blue low light.' },
  { id: '14', slug: 'white-tailed-deer', chapter: 'animals', o: 'L', body: 'A doe exploding into flight at the forest edge at dusk, white tail flagging high, a fawn bounding behind, motion and alarm.' },
  { id: '15', slug: 'coyote', chapter: 'animals', o: 'L', body: 'A coyote at the apex of a pounce on a vole in a snow-dusted field at dawn, forelegs down, breath fogging the cold air.' },
  { id: '16', slug: 'fisher', chapter: 'animals', o: 'P', body: 'A fisher descending a tree trunk headfirst in pursuit, claws gripping bark, body coiled and intent, dim forest.' },
  { id: '17', slug: 'bobcat', chapter: 'animals', o: 'L', body: 'A bobcat frozen mid-stalk low in tall amber autumn grass, weight loaded back, ears forward, an instant from springing, golden hour.' },
  { id: '19', slug: 'porcupine', chapter: 'animals', o: 'P', body: 'A porcupine high in the bare branches of a tree at dusk, silhouetted against a fading sky, gnawing buds, winter.' },
  { id: '20', slug: 'beaver', chapter: 'animals', o: 'L', body: 'A beaver swimming with a freshly-cut leafy branch in its mouth toward its lodge at twilight, a long V-wake spreading across still dark water.' },
  { id: '21', slug: 'river-otter', chapter: 'animals', o: 'L', body: 'A river otter caught mid-slide down a snowy bank into black water, joyful motion, spray, winter.' },
  { id: '22', slug: 'striped-skunk', chapter: 'animals', o: 'S', body: 'A striped skunk in full warning display at twilight: front feet stamped, back arched, tail flared high, the honest bluff.' },
  { id: '23', slug: 'snowshoe-hare', chapter: 'animals', o: 'L', body: 'A snowshoe hare at the peak of a bound across fresh snow in pure-white winter coat, oversized hind feet thrown forward.' },
  { id: '24', slug: 'common-loon', chapter: 'animals', o: 'S', body: 'A common loon floating low on a still lake at dawn, near-frontal, its brilliant glowing ruby-red eye catching the light, crisp black-and-white checkered plumage, soft mist on the water.' },
  { id: '26', slug: 'barred-owl', chapter: 'animals', o: 'L', body: 'A barred owl in silent low flight through misty old-growth forest, broad rounded wings fully spread, dark eyes fixed ahead, dusk fog.' },
  { id: '27', slug: 'wild-turkey', chapter: 'animals', o: 'L', body: 'A tom wild turkey in full strut display, tail fanned and feathers iridescent, in a spring clearing with last patches of melting snow.' },
  { id: '28', slug: 'peregrine-falcon', chapter: 'animals', o: 'P', body: 'A peregrine falcon in a full hunting stoop down a sheer cliff face, wings tucked, blurred with extreme speed.' },
  { id: '29', slug: 'timber-rattlesnake', chapter: 'animals', o: 'L', body: 'A timber rattlesnake basking with its long body extended and loosely looped across a sun-dappled forest floor of fallen leaves, full bold pattern and rattle shown, summer.' },
  { id: '30', slug: 'copperhead', chapter: 'animals', o: 'S', body: 'A copperhead coiled and nearly invisible in autumn leaf litter, tongue flicking, a single shaft of light finding its coppery hourglass bands.' },
  { id: '31', slug: 'snapping-turtle', chapter: 'animals', o: 'L', body: "A large snapping turtle's ancient head and algae-covered shell ridge breaking the still surface of a dark pond, ripples spreading, lily pads." },
  { id: '32', slug: 'wood-frog', chapter: 'animals', o: 'S', body: "A wood frog floating at the surface of a clear spring vernal pool among gelatinous egg masses, dark robber's-mask eyes just above the waterline." },
  { id: '33', slug: 'deer-tick', chapter: 'animals', o: 'S', body: 'A clean naturalist macro of a single deer tick perched on a grass blade — anatomically accurate with exactly eight legs, uncluttered composition, softly backlit at a sunlit trail edge, the small menace at heroic scale.' },
  { id: '34', slug: 'yellow-jacket', chapter: 'animals', o: 'S', body: 'A yellow jacket wasp banking in to land on its torn grey papery nest at a woodland edge, workers crawling, late-summer gold.' },
  { id: '35', slug: 'black-fly', chapter: 'animals', o: 'S', body: 'A backlit spring swarm of black flies hazing the air over a stream at dusk, one in sharp macro detail.' },
  { id: '36', slug: 'foragers-code', chapter: 'plants', o: 'L', body: "A forager's weathered basket and a hand-drawn field journal resting on a mossy log at golden hour, a few mixed wild greens and berries inside, dappled forest light — the forager's mindset, NOT a field of one species." },
  { id: '37', slug: 'wild-ramps', chapter: 'plants', o: 'S', body: 'A clump of wild ramps pulled half-free of dark soil clinging to the white bulbs, broad green leaves, dappled spring forest floor.' },
  { id: '38', slug: 'fiddlehead-fern', chapter: 'plants', o: 'S', body: 'Tight ostrich-fern fiddlehead crosiers unfurling, beaded with dew, backlit at a stream edge, spring dawn.' },
  { id: '39', slug: 'wild-blueberry', chapter: 'plants', o: 'L', body: 'A sun-baked summit blueberry barren reddening at the edges, low bushes heavy with ripe berries, mountains beyond, late summer.' },
  { id: '40', slug: 'highbush-blueberry', chapter: 'plants', o: 'S', body: 'A fruit-laden highbush blueberry branch arcing over dark still pond water, ripe clusters, summer.' },
  { id: '41', slug: 'wild-strawberry', chapter: 'plants', o: 'S', body: 'Tiny ruby wild strawberries low in a sunlit meadow, trifoliate leaves, one perfect dewdrop, early summer.' },
  { id: '42', slug: 'black-raspberry', chapter: 'plants', o: 'S', body: 'An arching bramble cane dense with dark ripe fruit at a forest edge, warm late-day light, summer.' },
  { id: '43', slug: 'wood-sorrel', chapter: 'plants', o: 'S', body: 'Delicate clover-like wood-sorrel leaves and one veined white flower glowing on the dark mossy forest floor.' },
  { id: '44', slug: 'sheep-sorrel', chapter: 'plants', o: 'L', body: 'A wind-bent stand of sheep sorrel reddening across an open field at golden hour, summer.' },
  { id: '45', slug: 'cattail', chapter: 'plants', o: 'L', body: 'A backlit stand of cattails at a marsh edge at sunset, brown seed-heads bursting into fluff, autumn.' },
  { id: '46', slug: 'stinging-nettle', chapter: 'plants', o: 'S', body: 'A stinging-nettle stand backlit so the fine stinging hairs glint, riverbank, flat morning light.' },
  { id: '47', slug: 'trout-lily', chapter: 'plants', o: 'S', body: 'Mottled trout-lily leaves and a single nodding yellow bloom on the brown spring forest floor, low light.' },
  { id: '48', slug: 'elderberry', chapter: 'plants', o: 'S', body: 'Heavy dark elderberry clusters drooping against the sky at a stream bank, late summer.' },
  { id: '49', slug: 'spruce-tips', chapter: 'plants', o: 'S', body: 'Bright lime-green new spruce tips against dark mature needles, beaded with dew, soft spring light.' },
  { id: '50', slug: 'yarrow', chapter: 'plants', o: 'S', body: 'A flat white yarrow flower-head crowded with morning dew, feathery foliage, meadow edge, summer dawn.' },
  { id: '51', slug: 'broadleaf-plantain', chapter: 'plants', o: 'S', body: 'A ribbed broadleaf-plantain rosette and upright seed spike growing in a sunlit gravel path crack, raindrops beading.' },
  { id: '52', slug: 'st-johns-wort', chapter: 'plants', o: 'S', body: "Bright yellow St. John's-wort star-flowers catching first sun in a dry summer field, one backlit." },
  { id: '53', slug: 'goldenrod', chapter: 'plants', o: 'L', body: 'A field of goldenrod blazing at golden hour, one sharp plume against soft glowing bokeh, late summer.' },
  { id: '54', slug: 'toxic-plants', chapter: 'plants', o: 'P', body: 'A shadowy mist-shrouded wet meadow at dusk where danger lurks — one tall, ominous dark plant silhouette against cold fading light, an atmospheric sense of botanical danger, NOT a labeled water-hemlock specimen.' },
  { id: '55', slug: 'water-hemlock', chapter: 'plants', o: 'S', body: 'Lacy white water-hemlock umbels glowing eerily against deep dark wetland shadow, sinister, overcast.' },
  { id: '56', slug: 'false-hellebore', chapter: 'plants', o: 'S', body: 'Bold pleated green false-hellebore leaves unfurling like a trap in a foggy spring seep.' },
  { id: '57', slug: 'wild-parsnip', chapter: 'plants', o: 'L', body: 'Yellow wild-parsnip umbels backlit by harsh sun casting hard shadows, the phototoxic burn implied by the severe light.' },
  { id: '58', slug: 'poison-sumac', chapter: 'plants', o: 'L', body: 'Flame-red poison-sumac autumn foliage over black swamp water, beautiful and forbidding.' },
  { id: '59', slug: 'poison-ivy', chapter: 'plants', o: 'S', body: 'Glossy leaves-of-three poison ivy climbing a tree trunk in vivid autumn red, menacing.' },
  { id: '60', slug: 'baneberry', chapter: 'plants', o: 'S', body: "White doll's-eyes baneberries on thick red stalks staring out from deep forest shadow." },
  { id: '61', slug: 'jimsonweed', chapter: 'plants', o: 'P', body: 'A single moonlit white jimsonweed trumpet flower opening at dusk above its spiny seed pod, eerie.' },
  { id: '62', slug: 'eastern-white-pine', chapter: 'trees', o: 'P', body: 'A lone giant white pine towering far above the surrounding canopy against piled dramatic storm clouds, branches moving in wind.' },
  { id: '63', slug: 'sugar-maple', chapter: 'trees', o: 'P', body: 'A single sugar maple in peak autumn fire perfectly mirrored in a still pond, calm.' },
  { id: '64', slug: 'yellow-birch', chapter: 'trees', o: 'P', body: 'Curling golden-bronze yellow-birch bark catching low light, roots straddling a mossy boulder over a brook, autumn.' },
  { id: '65', slug: 'paper-birch', chapter: 'trees', o: 'P', body: 'Luminous white paper-birch trunks in a grove after rain, wet bark gleaming, spring.' },
  { id: '66', slug: 'american-beech', chapter: 'trees', o: 'P', body: 'Smooth grey beech trunks holding coppery marcescent leaves as the first snow falls, winter.' },
  { id: '67', slug: 'balsam-fir', chapter: 'trees', o: 'P', body: 'A dark balsam-fir spire against a pale winter sky on a snowy ridge, snow-laden boughs.' },
  { id: '68', slug: 'red-spruce', chapter: 'trees', o: 'P', body: 'A wind-sculpted red spruce at the krummholz treeline edge with mist tearing past, mountain.' },
  { id: '69', slug: 'eastern-hemlock', chapter: 'trees', o: 'P', body: "A mature eastern hemlock's layered, gracefully drooping boughs over a shaded brook, one shaft of light, small cones, summer." },
  { id: '70', slug: 'tamarack-larch', chapter: 'trees', o: 'L', body: 'Golden tamarack needles raining down into the black mirror of a misty bog at dawn, autumn.' },
  { id: '71', slug: 'quaking-aspen', chapter: 'trees', o: 'P', body: 'Quaking-aspen leaves shimmering and flashing pale in a gust, low autumn sun behind, white bark.' },
  { id: '72', slug: 'black-cherry', chapter: 'trees', o: 'S', body: 'Dark scaly black-cherry bark and drooping clusters of small dark fruit at a forest edge, a bird-pecked branch, late summer.' },
  { id: '73', slug: 'striped-maple', chapter: 'trees', o: 'P', body: 'Vivid green-and-white striped maple bark standing out in a grey winter understory, snow at its base.' },
  { id: '74', slug: 'red-oak', chapter: 'trees', o: 'L', body: 'A massive lone red oak in a field holding its rust-red leaves, acorns scattered below, late-autumn light.' },
  { id: '75', slug: 'mycologist-protocol', chapter: 'fungi', o: 'S', body: "A naturalist's mushroom-study still life on a wooden table: a spore print on paper, a brass hand lens, a small knife, and a basket of a few assorted unidentified mushrooms — the careful identification mindset, NOT a single hen-of-the-woods." },
  { id: '76', slug: 'hen-of-the-woods', chapter: 'fungi', o: 'S', body: 'Overlapping grey-brown maitake fronds bursting from the base of a great oak among fallen autumn leaves.' },
  { id: '77', slug: 'chicken-of-the-woods', chapter: 'fungi', o: 'S', body: 'Vivid orange-and-yellow chicken-of-the-woods shelves glowing on a dark mossy log, summer.' },
  { id: '78', slug: 'giant-puffball', chapter: 'fungi', o: 'L', body: 'A huge white giant-puffball sphere startling in a dewy green meadow at dawn, late summer.' },
  { id: '79', slug: 'chanterelle', chapter: 'fungi', o: 'S', body: 'Golden chanterelle trumpets glowing scattered on the dark mossy forest floor, one sunbeam finding them, summer.' },
  { id: '80', slug: 'oyster-mushroom', chapter: 'fungi', o: 'S', body: 'Tiered grey oyster-mushroom caps fanning up a dead trunk, soft side light after rain, autumn.' },
  { id: '81', slug: 'lions-mane', chapter: 'fungi', o: 'S', body: "A cascade of white icicle-like lion's-mane spines on a hardwood wound in dim forest, autumn." },
  { id: '82', slug: 'morel', chapter: 'fungi', o: 'S', body: 'A honeycomb-ridged morel half-hidden in spring leaf litter near a dead elm, dappled light.' },
  { id: '83', slug: 'honey-mushroom', chapter: 'fungi', o: 'S', body: 'A dense cluster of honey-tan mushroom caps swarming the base of a hardwood stump in low gold autumn light.' },
  { id: '84', slug: 'shaggy-mane', chapter: 'fungi', o: 'P', body: 'A row of shaggy white inky-cap caps emerging through gravel at dusk, one already deliquescing to black ink, autumn.' },
  { id: '85', slug: 'deadly-fungi', chapter: 'fungi', o: 'S', body: 'A dark, mist-shrouded forest floor at dusk where a few pale, ghostly mushrooms emerge from deep shadow, cold ominous light and an atmospheric sense of hidden danger — a wider establishing mood, NOT a single Amanita specimen.' },
  { id: '86', slug: 'destroying-angel', chapter: 'fungi', o: 'P', body: 'A pure-white destroying-angel amanita rising from dark forest duff in faint cold light, lethal elegance.' },
  { id: '87', slug: 'death-cap', chapter: 'fungi', o: 'S', body: 'A greenish-capped death-cap amanita with its membranous skirt and basal cup, half in shadow, sinister calm.' },
  { id: '88', slug: 'galerina', chapter: 'fungi', o: 'S', body: 'A small brown galerina cluster on a mossy fallen log, deceptively ordinary, menacing low light, autumn.' },
  { id: '89', slug: 'jack-o-lantern', chapter: 'fungi', o: 'S', body: "A cluster of orange jack-o'-lantern mushrooms at a stump in near-darkness, hinting at an eerie green bioluminescent glow, autumn night." },
  { id: '90', slug: 'false-morel', chapter: 'fungi', o: 'S', body: 'A reddish-brown brain-like false-morel cap on the spring forest floor, ominous and isolated.' },
  { id: '91', slug: 'glacial-inheritance', chapter: 'terrain', o: 'L', body: 'A cinematic cross-section cutaway of a glacier-carved valley — the ice gone, revealing the U-shaped land, moraines, and erratics it left.' },
  { id: '92', slug: 'ridgelines', chapter: 'terrain', o: 'L', body: 'A serrated mountain ridgeline receding in fading blue layers into hazy distance, reading the skyline.' },
  { id: '93', slug: 'zones-underfoot', chapter: 'terrain', o: 'S', body: 'A boots-eye ground-level view where soft spruce duff meets pale alpine lichen-rock exactly at the treeline boundary.' },
  { id: '94', slug: 'noreasters', chapter: 'terrain', o: 'L', body: "A nor'easter slamming a wind-bent spruce ridge above a cold grey churning Atlantic, driving snow, dangerous, winter." },
  { id: '95', slug: 'above-treeline-whites', chapter: 'terrain', o: 'L', body: 'The Presidential Range armored in white rime ice under a violent racing sky, brutal alpine exposure, winter.' },
  { id: '96', slug: 'fog', chapter: 'terrain', o: 'L', body: 'Thick coastal summit fog pouring over a forested ridge and swallowing the trees, a single dark treetop adrift in white.' },
  { id: '97', slug: 'northern-boreal', chapter: 'terrain', o: 'L', body: 'Endless near-identical spruce in flat featureless fog, a faint game trail dissolving into the murk, disorientation.' },
  { id: '98', slug: 'alpine-subalpine', chapter: 'terrain', o: 'L', body: 'A lone summit cairn standing above an endless sea of cloud at sunrise, vast sky.' },
  { id: '99', slug: 'hardwood-corridor', chapter: 'terrain', o: 'L', body: 'A leaf-strewn trail forking in dense autumn hardwood forest, low sun raking through the trunks.' },
  { id: '100', slug: 'finding-water', chapter: 'terrain', o: 'S', body: 'A clear cold spring trickling from mossy alpine rock into a small pool, intimate, summer.' },
  { id: '101', slug: 'beaver-ponds-giardia', chapter: 'terrain', o: 'L', body: 'A still tannin-dark beaver pond at dusk with a beaver lodge silhouetted, marsh grasses, beautiful but quietly cautionary.' },
  { id: '102', slug: 'river-crossings-snowmelt', chapter: 'terrain', o: 'P', body: 'Close on fast clear snowmelt water surging around shin-deep wading legs and a probing pole, cold spray, spring.' },
  { id: '103', slug: 'map-compass', chapter: 'terrain', o: 'S', body: 'A hand laying a brass compass on a topographic map spread across a sunlit rock, a ridgeline beyond.' },
  { id: '104', slug: 'dead-reckoning', chapter: 'terrain', o: 'L', body: 'A lone figure sighting a compass bearing through dim, crowded spruce, overcast.' },
  { id: '105', slug: 'terrain-association', chapter: 'terrain', o: 'L', body: 'A hiker matching a distinct rocky peak ahead to a map, sweeping alpine view, clear day.' },
  { id: '106', slug: 'tech-fails', chapter: 'terrain', o: 'L', body: 'A dead phone being pocketed as map-and-compass come out at a trail junction, fog rolling in at dusk, expedition-journal mood.' },
  { id: '107', slug: 'mud-season', chapter: 'terrain', o: 'L', body: 'A thaw-soaked muddy trail mirroring bare grey trees and a snow-streaked peak, raw early spring.' },
  { id: '108', slug: 'stick-season', chapter: 'terrain', o: 'L', body: 'Bare grey-brown November hardwoods under a cold mountain, the silent quiet between seasons, overcast.' },
  { id: '109', slug: 'survival-priorities', chapter: 'survival', o: 'L', body: 'A calm forest-floor field study laying out the four lifelines together — emergency shelter, fire, water, and a signal — a cohesive naturalist arrangement.' },
  { id: '110', slug: 'shelter', chapter: 'survival', o: 'L', body: 'A finished debris-hut lean-to of branches, bark, and spruce boughs packed with thick leaf litter against a fallen log at dusk, a small fire glowing nearby.' },
  { id: '111', slug: 'water', chapter: 'survival', o: 'S', body: 'Hands collecting clear water from a mossy spring through an improvised cloth-and-charcoal filter into a container, droplets falling.' },
  { id: '112', slug: 'fire', chapter: 'survival', o: 'S', body: 'A tinder bundle bursting into its first flame in cupped hands, sparks rising, a ferro rod and knife on the forest floor, dim dusk.' },
  { id: '113', slug: 'signaling', chapter: 'survival', o: 'L', body: 'Three signal fires arranged in a triangle in an open clearing at dusk, smoke rising, a signal-mirror flash aimed at a distant ridge.' },
  { id: '114', slug: 'first-aid', chapter: 'survival', o: 'S', body: 'Hands binding an improvised splint of cloth strips and a straight branch on the forest floor, a compact kit open nearby.' },
  { id: '115', slug: 'self-rescue', chapter: 'survival', o: 'L', body: 'A lone hiker paused at a river-crossing decision, a paper map in hand, weighing the route, ridgelines beyond, overcast.' },
  { id: '116', slug: 'white-mountain-amc', chapter: 'survival', o: 'L', body: 'A high alpine stone hut against a hostile dusk sky, one warm lit window, weather building over the range.' },
  { id: '117', slug: 'fire-from-land', chapter: 'bushcraft', o: 'S', body: 'A bow-drill friction set at the exact instant a glowing ember drops into a tinder bundle of dry grass and birch bark, smoke curling, hands working.' },
  { id: '118', slug: 'shelter-from-land', chapter: 'bushcraft', o: 'L', body: 'A cinematic cutaway of a natural debris-hut shelter showing the ridgepole, ribbing, and thick leaf-litter insulation in cross-section, forest.' },
  { id: '119', slug: 'water-from-land', chapter: 'bushcraft', o: 'S', body: 'A clear transpiration bag fogged with droplets tied over green leafy foliage, sun behind, with a birch-tap dripping sap into a container.' },
  { id: '120', slug: 'food-from-land', chapter: 'bushcraft', o: 'L', body: "A forager's haul of New England wild edibles — cattail, acorns, wild greens, berries, edible roots — laid out on a mossy log at golden hour." },
  { id: '121', slug: 'first-aid-from-land', chapter: 'bushcraft', o: 'S', body: 'A wild first-aid still life on a mossy log in warm light: fresh-crushed plantain and yarrow leaves, a small mound of poultice, a drop of golden pine resin, and a clean rolled cloth bandage.' },
  { id: '122', slug: 'cordage-tools', chapter: 'bushcraft', o: 'S', body: 'Weathered hands twisting strands of bark fiber into strong cordage, raw fibers fraying, warm light.' },
  { id: '123', slug: 'bushcraft-mindset', chapter: 'bushcraft', o: 'L', body: 'A lone figure at a small fire at dusk where boreal forest meets an open meadow, settled and at home in the wild, warm glow.' },
  { id: '124', slug: 'batoning', chapter: 'bushcraft', o: 'S', body: 'A fixed-blade knife being driven through a split log by a wooden baton, dry inner wood exposed, chips flying, forest.' },
  { id: '125', slug: 'essential-knots', chapter: 'bushcraft', o: 'S', body: 'Four bushcraft knots tied in natural cordage on weathered wood in warm raking firelight, a craft still-life.' },
  { id: '126', slug: 'wood-carving', chapter: 'bushcraft', o: 'S', body: 'Hands whittling a wooden spoon with a knife, curls of shaving falling, carved camp tools arranged on a work block, warm light.' },
  { id: '127', slug: 'reading-weather', chapter: 'bushcraft', o: 'L', body: 'A dramatic sky study: high wispy cirrus giving way to a building storm front over a New England range, wind moving the trees.' },
];
