/**
 * Vendor the PREFORMATTED / CODE face from a local TTF.
 *
 * Deliberately separate from `vendor-fonts.ts`, for two reasons.
 *
 * 1. SOURCE. The body and display faces come from Google Fonts. This one cannot:
 *    Google's webfont builds ship latin/greek/cyrillic/vietnamese subsets only,
 *    and the glyphs this face exists for — box drawing U+2500-257F and block
 *    elements U+2591/U+2593 — are absent from every one of them. Measured across
 *    JetBrains Mono, Noto Sans Mono, IBM Plex Mono, Source Code Pro and Roboto
 *    Mono: all missing 18 of the 22 characters in DIRT RICH's Appendix E, as are
 *    all eleven faces already vendored here. The TTF is committed instead.
 *
 * 2. SUBSETTING. `vendor-fonts.ts` filters to latin subsets. Running this face
 *    through that path would strip exactly the glyphs it was vendored for. So
 *    the whole font is inlined, with NO unicode-range at all.
 *
 * The cost is ~450KB of base64 in the stylesheet. It is only emitted for a book
 * whose standard declares a `preformatted` policy, so a text-only book carries
 * none of it.
 *
 *   yarn tsx scripts/vendor-mono-font.ts
 *
 * Source: DejaVu Fonts 2.37, official unmodified release.
 *   https://github.com/dejavu-fonts/dejavu-fonts/releases/tag/version_2_37
 *   ttf/DejaVuSansMono.ttf  sha256 b4a6c3e4faab8773f4ff761d56451646409f29abedd68f05d38c2df667d3c582
 * Licence: assets/fonts/DejaVuSansMono-LICENSE.txt (Bitstream Vera / Public
 * Domain terms; embedding and redistribution permitted).
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(ROOT, 'assets', 'fonts');

export const MONO_FAMILY = 'DejaVu Sans Mono';
export const MONO_TTF = path.join(FONT_DIR, 'ttf', 'DejaVuSansMono.ttf');
/** The official 2.37 regular. Verified on vendoring; a mismatch is a hard stop. */
export const MONO_SHA256 = 'b4a6c3e4faab8773f4ff761d56451646409f29abedd68f05d38c2df667d3c582';

const ttf = readFileSync(MONO_TTF);
const sha = createHash('sha256').update(ttf).digest('hex');
if (sha !== MONO_SHA256) {
  throw new Error(
    `${MONO_FAMILY}: expected sha256 ${MONO_SHA256}, got ${sha}. ` +
      `This must be the unmodified official 2.37 release — re-download rather than adjusting the constant.`,
  );
}

/**
 * Regular weight only. This face sets fenced blocks and nothing else; there is
 * no bold or italic preformatted content in any book on the platform, and each
 * additional weight is another ~450KB of base64 for glyphs never set.
 */
const css = [
  `/* ${MONO_FAMILY} — vendored from the official DejaVu 2.37 TTF, COMPLETE (no`,
  `   subsetting), base64 inlined. Generated by backend/scripts/vendor-mono-font.ts.`,
  `   Do not hand-edit, and do not route this face through vendor-fonts.ts: its`,
  `   latin-only filter would remove the box-drawing glyphs this face exists for.`,
  `   Licence: DejaVuSansMono-LICENSE.txt */`,
  `@font-face{font-family:'${MONO_FAMILY}';font-style:normal;font-weight:400;font-display:block;` +
    `src:url(data:font/ttf;base64,${ttf.toString('base64')}) format('truetype');}`,
].join('\n');

const out = path.join(FONT_DIR, 'dejavu-sans-mono.css');
writeFileSync(out, css + '\n', 'utf8');
console.log(
  `${MONO_FAMILY}: ${Math.round(ttf.length / 1024)} KB ttf -> ${Math.round(Buffer.byteLength(css) / 1024)} KB css` +
    `  (complete, no unicode-range)  -> ${path.relative(ROOT, out)}`,
);
