/**
 * Vendor the typeset display/text faces into the repo as self-contained CSS.
 *
 * WHY: the typeset HTML currently <link>s Google Fonts, so the printed interior
 * depends on a CDN being reachable at render time. If that request stalls or
 * fails, Chromium silently falls back to a generic face and the PDF that goes to
 * the printer is not the book anyone approved. Print output must be
 * deterministic and reproducible offline.
 *
 * Output: backend/assets/fonts/<slug>.css — @font-face rules whose src is a
 * base64 data: URI, so nothing is fetched at render time. Run this when adding a
 * face; commit the result.
 *
 *   yarn workspace @wildlands/backend vendor:fonts
 */
import path from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(ROOT, 'assets', 'fonts');

/** Families offered by Book Setup. Keep in sync with HEADING_FONTS/BODY_FONTS. */
const FAMILIES = ['Oswald', 'Archivo', 'Montserrat', 'EB Garamond', 'Cormorant Garamond', 'Lora'];

/** The roles the typeset CSS actually uses: 400/500/600, upright + italic. */
const AXIS = 'ital,wght@0,400;0,500;0,600;1,400;1,600';

/** A UA new enough that Google serves woff2 rather than ttf. */
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/**
 * Latin only. Google splits each face into subsets (cyrillic, greek, vietnamese,
 * …); an English-language book needs latin + latin-ext, and shipping the rest
 * would multiply the committed bytes for glyphs the book never sets.
 */
function isLatinSubset(unicodeRange: string): boolean {
  return unicodeRange.includes('U+0000-00FF') || unicodeRange.includes('U+0100-02BA');
}

export function slugify(family: string): string {
  return family.toLowerCase().replace(/\s+/g, '-');
}

async function vendor(family: string): Promise<void> {
  const cssUrl = `https://fonts.googleapis.com/css2?family=${family.replace(/\s+/g, '+')}:${AXIS}&display=swap`;
  const css = await fetch(cssUrl, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error(`${family}: css2 responded ${r.status}`);
    return r.text();
  });

  const blocks = css.split('@font-face').slice(1);
  const out: string[] = [
    `/* ${family} — vendored from Google Fonts, latin subsets, base64 inlined.`,
    `   Generated by backend/scripts/vendor-fonts.ts. Do not hand-edit. */`,
  ];
  let kept = 0;

  for (const block of blocks) {
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? '';
    if (range && !isLatinSubset(range)) continue;
    const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
    if (!url) continue;
    const style = /font-style:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? 'normal';
    const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? '400';

    const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
    out.push(
      `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:block;` +
        `src:url(data:font/woff2;base64,${bytes.toString('base64')}) format('woff2');` +
        (range ? `unicode-range:${range};` : '') +
        `}`,
    );
    kept++;
  }

  if (kept === 0) throw new Error(`${family}: no latin faces resolved`);
  const file = path.join(OUT_DIR, `${slugify(family)}.css`);
  await writeFile(file, out.join('\n') + '\n', 'utf8');
  const kb = Math.round(Buffer.byteLength(out.join('\n')) / 1024);
  console.log(`  ${family.padEnd(20)} ${String(kept).padStart(2)} faces  ${String(kb).padStart(4)} KB  -> ${path.relative(ROOT, file)}`);
}

await mkdir(OUT_DIR, { recursive: true });
console.log('vendoring typeset fonts (latin subsets, base64 inlined):');
for (const family of FAMILIES) await vendor(family);
console.log('done.');
