/**
 * Serve the typeset faces from vendored assets instead of the Google Fonts CDN.
 *
 * A printed interior must be reproducible: the same manuscript and config have
 * to produce the same PDF next month, offline, on a build box with no egress. A
 * <link> to fonts.googleapis.com breaks that — a stalled or blocked request
 * makes Chromium quietly substitute a generic face, and the file that reaches
 * the printer is not the book that was approved. Nothing about that failure is
 * visible in a page count or an overflow check.
 *
 * Assets are generated by backend/scripts/vendor-fonts.ts and committed.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** backend/assets/fonts — same relative depth from src/ and from dist/. */
const FONT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../assets/fonts');

const cache = new Map<string, string | null>();

export function fontSlug(family: string): string {
  return family.toLowerCase().replace(/\s+/g, '-');
}

/** The vendored @font-face CSS for one family, or null when it is not bundled. */
function loadFamily(family: string): string | null {
  const slug = fontSlug(family);
  const hit = cache.get(slug);
  if (hit !== undefined) return hit;
  let css: string | null;
  try {
    css = readFileSync(path.join(FONT_DIR, `${slug}.css`), 'utf8');
  } catch {
    css = null;
  }
  cache.set(slug, css);
  return css;
}

export interface BundledFonts {
  /** @font-face rules to inline in <style>. Empty when nothing is bundled. */
  css: string;
  /** Families served from the repo. */
  bundled: string[];
  /** Families with no vendored asset — these still need the CDN. */
  missing: string[];
}

/**
 * Resolve the requested families against the vendored assets. Duplicates are
 * collapsed so a book whose heading and body face match embeds one copy.
 */
export function bundledFontCss(families: string[]): BundledFonts {
  const unique = [...new Set(families.filter(Boolean))];
  const parts: string[] = [];
  const bundled: string[] = [];
  const missing: string[] = [];

  for (const family of unique) {
    const css = loadFamily(family);
    if (css) {
      parts.push(css);
      bundled.push(family);
    } else {
      missing.push(family);
    }
  }

  return { css: parts.join('\n'), bundled, missing };
}
