/**
 * Serve the typeset faces from vendored assets instead of the Google Fonts CDN.
 *
 * A printed interior must be reproducible: the same manuscript and config have
 * to produce the same PDF next month, offline, on a build box with no egress. A
 * <link> to fonts.googleapis.com breaks that — a stalled or blocked request
 * makes Chromium quietly substitute a generic face, and the file that reaches
 * the printer is not the book that was approved. Nothing about that failure is
 * visible in a page count or an overflow check.
 *
 * Assets are generated by backend/scripts/vendor-fonts.ts and committed.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** backend/assets/fonts — same relative depth from src/ and from dist/. */
const FONT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../assets/fonts');

const cache = new Map<string, string | null>();

export function fontSlug(family: string): string {
  return family.toLowerCase().replace(/\s+/g, '-');
}

/** The vendored @font-face CSS for one family, or null when it is not bundled. */
function loadFamily(family: string): string | null {
  const slug = fontSlug(family);
  const hit = cache.get(slug);
  if (hit !== undefined) return hit;
  let css: string | null;
  try {
    css = readFileSync(path.join(FONT_DIR, `${slug}.css`), 'utf8');
  } catch {
    css = null;
  }
  cache.set(slug, css);
  return css;
}

export interface BundledFonts {
  /** @font-face rules to inline in <style>. Empty when nothing is bundled. */
  css: string;
  /** Families served from the repo. */
  bundled: string[];
  /** Families with no vendored asset — these still need the CDN. */
  missing: string[];
  /** Families resolved from the host's font path instead of @font-face. */
  systemInstalled: string[];
}

/**
 * SYSTEM-INSTALLED FAMILIES — the reason the interior can embed real fonts.
 *
 * Chromium converts ANY `@font-face` into Type3 glyph-drawing procedures, which
 * print RIPs commonly reject, and emits proper embedded Type0 CID subsets only
 * for fonts in the host's font path. Proven both ways in
 * `scripts/font-embed-probe.ts`. So on a host where a family is installed we
 * must NOT emit an `@font-face` for it — doing so wins over the system font and
 * puts us straight back to Type3.
 *
 * The render image installs the same faces the vendored stylesheets carry
 * (`scripts/derive-ttf.ts` decompresses them, so the glyph data is identical
 * and pagination cannot move). Windows dev boxes have none of them installed
 * and keep using the vendored CSS, which is correct there: local renders are
 * for layout review, not for print.
 */
let systemFamiliesCache: Set<string> | null = null;

function systemFamilies(): Set<string> {
  if (systemFamiliesCache) return systemFamiliesCache;
  const found = new Set<string>();
  try {
    // fontconfig is the authority on what this host can actually resolve.
    // Absent (Windows, or a slim image) means "nothing installed", which is the
    // safe answer: we fall back to the vendored @font-face and Layer 1's font
    // audit still fails loudly rather than shipping a silent substitution.
    const out = execFileSync('fc-list', ['--format', '%{family}\n'], {
      encoding: 'utf8',
      timeout: 10_000,
    });
    for (const line of out.split('\n')) {
      for (const name of line.split(',')) {
        const n = name.trim();
        if (n) found.add(n.toLowerCase());
      }
    }
  } catch {
    // No fontconfig — treat as no system fonts.
  }
  systemFamiliesCache = found;
  return found;
}

/** Test seam: forget what fontconfig said. */
export function resetSystemFontCache(): void {
  systemFamiliesCache = null;
}

export function isSystemInstalled(family: string): boolean {
  return systemFamilies().has(family.trim().toLowerCase());
}

/**
 * Resolve the requested families against the vendored assets. Duplicates are
 * collapsed so a book whose heading and body face match embeds one copy.
 */
export function bundledFontCss(families: string[]): BundledFonts {
  const unique = [...new Set(families.filter(Boolean))];
  const parts: string[] = [];
  const bundled: string[] = [];
  const missing: string[] = [];
  const systemInstalled: string[] = [];

  for (const family of unique) {
    // A family the host can resolve itself must be left to the host: emitting
    // an @font-face for it would override the installed face and hand us Type3.
    if (isSystemInstalled(family)) {
      systemInstalled.push(family);
      continue;
    }
    const css = loadFamily(family);
    if (css) {
      parts.push(css);
      bundled.push(family);
    } else {
      missing.push(family);
    }
  }

  return { css: parts.join('\n'), bundled, missing, systemInstalled };
}
